### ISSUE TITLE
Hints to how to fix errors in the generated output

### ISSUE THREAD

**Issue by WeirdRubberDuck** [WandrilleD/csv-to-openSpace#1]
Helped Takanori load an example asset based on this code and found some problems in the generated output. 

This line: https://github.com/WandrilleD/csv-to-openSpace/blob/2556c8b1598febe9c4709c3f4f3271c98641a846/output/toy_data.asset#L11

 has an extra ".speck". Should be: 
 ```
 local speck_file = asset.localResource("toy_data.speck")
 ```
 
 And this line: https://github.com/WandrilleD/csv-to-openSpace/blob/2556c8b1598febe9c4709c3f4f3271c98641a846/output/toy_data.asset#L25
 
 uses the file name instead of the variable name (of the Lua variable on line 14). Should be: 
 ```
 LabelFile = label_file_cell_line,
 ```
 
 Also, the example colormap has too few colors to represent the given color ranges and values. It does not interpolate between the different colors in the camp file, but instead you need a cmpa file with at least as many color samples as the value range you want to represent. Just FYI
 
 I hope this is helpful :)

**Comment by WandrilleD** [comment]
Thanks a lot for reviewing and suggesting these corrections!

The first two points you mention have been corrected.
Regarding the Cmap issue, I thought openSpace handled the interpolation. My issue is that I want to have a single cmap file for several data column. 
So would I need to create a cmap which has enough colors such that it is divisible by the number of categories in each columns. 
eg, if I have a column with 7 categories and another with 3 categories, then my cmap would need 3*7=21 colors?

**Comment by WeirdRubberDuck** [comment]
Yes, exactly

You could really see the values as "pixels" in the colormap. The more pixels you have, the more colors the interpolation will be able to choose from. 

You could for example create the colormap you want using Matplotlib and then sample that with a sufficiently high resolution.  It's no problem to have more colors than the values needed, so I would rather use too many samples than too few

**Comment by WandrilleD** [comment]
I've implemented something that creates a colormap whose number of columns depends on the number of categories in each columns.
There is a default to a max of 16 category per column but in practice that can be changed easily.
